### ISSUE TITLE
Calculate travel demand on bus routes

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [Hussein-Mahfouz/drt-potential#17]
Demand at the OD level is processed using issue #4 and PR #14 

How do we project this demand from the OD level to the route level? Currently I am using two different methods. Take an OD pair with demand = 20 that is served by 3 routes: Route A (freq = 6 buses/hour), Route B (freq = 3/hr, Route C (freq = 3/hr):

- Method 1 (All-to-all): If an OD pair has demand = 20 and is served by two direct routes, each of these routes is assigned the 20
- Method 2 (Frequency-based): Demand (Route A) = Total Demand * freq A / sum(freq A, freq B, freq C) = (20 * 6) / 12 = 10

**Comment by Hussein-Mahfouz** [comment]
- Method 1 (all-to-all) has much higher numbers as there is redundancy - it could show what demand on route X could be if it was the only route offering a service for the ODs that it passes through. 
- Method 2 is a better reflection of what the actual demand is 

Which method suits our purpose better?

![image](https://github.com/Hussein-Mahfouz/drt-potential/assets/45176416/77566826-a2b3-40c1-b964-591387d2fe69)

**Comment by Robinlovelace** [comment]
Without much context, method 2 seems to work well, what's the downside?

**Comment by Hussein-Mahfouz** [comment]
This is my current (incomplete) thinking. If we are looking at which bus routes to remove, then is it better to look at:

- (a) the maximum potential demand on the route (i.e. the demand that could be satisfied directly by the route if there was no other service) OR
- (b) an estimate of the actual demand on the route, given the current network **
- (c) an all-or-nothing approach (not done above): all demand assigned to highest frequency route only

(a) could give us a ceiling for the demand on a route, and we could combine it with another step - identifying the total demand that is _uniquely_* served by each route - to inform which routes are more important and which are redundant

(*) demand between A-B is uniquely served by a route X if it is the only route that goes directly from A to B

(**) Approach from chapter 10 of [Modelling Transport](https://onlinelibrary.wiley.com/doi/book/10.1002/9781119993308)

![image](https://github.com/Hussein-Mahfouz/drt-potential/assets/45176416/53609f6b-f5d2-43f3-9f99-d059f773f852)

**Comment by Hussein-Mahfouz** [comment]
![image](https://github.com/Hussein-Mahfouz/drt-potential/assets/45176416/a08fca45-da37-4ba7-bf89-af4fdef5c942)

**Comment by Hussein-Mahfouz** [comment]
The _multi-path_ approach in the last comment can be calculated using Aequilibria, see relevant documentation [here](https://www.aequilibrae.com/python/latest/modeling_with_aequilibrae/transit_assignment/transit_graph.html)

**Comment by Robinlovelace** [comment]
:+1:
