### ISSUE TITLE
Aggregating flows onto shortest paths 

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [Hussein-Mahfouz/drt-potential#26]
This is linked to #16 and is part of a method suggested by @mem48 . I am documenting here so that it is easy to transfer to any document I am writing 

_1. Run shortest path calculations for all OD pairs and retained the geometries: code [here](https://github.com/Hussein-Mahfouz/drt-potential/blob/76e6ecafda6de1d3e71781d21a70127bbfca5219/code/routing_r5r.R#L166-L181)_

_2. Keep only OD pairs with no direct bus between them. The number of transfers is obtained from the routing engine_

_3. Aggregate flows at road segment level_ 
    - Option 1 (name on map = overline): Overline with simplify = TRUE   
    - Option 2 (name on map = overline_merge): 
        - Step 1: Overline with simplify = FALSE to retain vertices (see [details](https://docs.ropensci.org/stplanr/reference/overline.html#details))
        - Simplify graph to merge parallel lines (using sfnetworks) - function is [here](https://github.com/Hussein-Mahfouz/drt-potential/blob/7c7361c5f2e21701e2d72b091def303047a5cf8b/R/simplify_graph.R)

_4. Identify intervention:_
    - corridors with concentrated demand (these need a new / better bus routes) 
    - areas with low / dispersed demand (a DRT service could suit these areas better)
    
#### Overline (Option 1)
    
![map_aggregate_flows_overline_vs_base](https://github.com/Hussein-Mahfouz/drt-potential/assets/45176416/5418f695-4e09-41e1-815b-f9cebaf6141d)

#### Overline (Option 1) vs Overline + Merge (Option 2)

![map_aggregate_flows_overline_vs_merge](https://github.com/Hussein-Mahfouz/drt-potential/assets/45176416/bd0585a0-fb86-4eaa-bd04-4ea42d3a0584)

It looks like the merging after overline is only having a minor effect. The merging function is not working very well. See the zoomed in screenshot as an example of partial merging but also unwanted edits to the network structure (I can't upload an html file here for browsing the results)

![image](https://github.com/Hussein-Mahfouz/drt-potential/assets/45176416/e2de67d6-9478-49d9-b277-2ce0f3f79f02)
 
I could work on editing the simplify_graph function, but it will be a time sink and I think for now overline is sufficient. Merging functionality is being addressed by https://github.com/nptscot/networkmerge. @Robinlovelace do you think it would be easy to use the functions from that work?

**Comment by Robinlovelace** [comment]
> I could work on editing the simplify_graph function, but it will be a time sink and I think for now overline is sufficient. Merging functionality is being addressed by https://github.com/nptscot/networkmerge. @Robinlovelace do you think it would be easy to use the functions from that work?

Sounds be easy and there's an issue to make it even easier that should be fixed at some point: https://github.com/nptscot/networkmerge/issues/97

Do you have a minimal example of a network in need of simplification? Half the battle is re-joining the attributes to the simplified network but that should be sorted by `rnet_merge()`: https://docs.ropensci.org/stplanr/reference/rnet_merge.html

**Comment by Robinlovelace** [comment]
OK, ideal test case for something I'm looking at with @wangzhao0217.. Will aim to get back but may not be until next week.

**Comment by Hussein-Mahfouz** [comment]
Another thing I could do is to concentrate the demand onto the main roads by either:
- using a weighted graph with weights that prioritise main roads (trunk, primary, secondary etc) - probably though dodgr
- downloading an osm.pbf files with only specific road types (e.g. without residential roads

Both of these would concentrate demand more while giving an indication of high-demand arteries

**Comment by anisotropi4** [comment]
I have done some work with network simplification (https://github.com/anisotropi4/arctic-tern) and aggregating rail passenger travel flows onto a rail centre-line track-model (https://github.com/anisotropi4/kingfisher).

I don't know if this is of interest but @Robinlovelace suggested I ought to mention this as it might be.

**Comment by Robinlovelace** [comment]
Heads-up @Hussein-Mahfouz here's the network merge code I wrote to join attributes to simplified geometry: https://github.com/nptscot/networkmerge/blob/101-test-for-road-network-in-leeds/test-osm-simplify-open-roads.qmd (OS Open Roads in this case)

**Comment by Hussein-Mahfouz** [comment]
Thanks @anisotropi4 and @Robinlovelace  ! 

@anisotropi4  I'll go through the links and may come back with questions
