### ISSUE TITLE
Spatial clustering of flow data 

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [Hussein-Mahfouz/drt-potential#27]
Clustering flow data can show where demand is concentrated. This can be overlaid on PT supply to identify gaps. Try:

**First pass**

- spatial clustering using planar flow data 
- independent clustering for car and PT flows

**Second (more ambitious) pass**

- Bivariate clustering to look at car and pt flow simultaneously
- Construct density domain (High-Car High-Bus, Low-Car High-Bus, High-Car-Low-Bus, Low-Car-Low-Bus)

**Limitations to mention**

- No temporal aspect (there are methods for it)
- check notion doc

**Comment by Robinlovelace** [comment]
Also: you could try just aggregating origins *or* destinations to make it simpler.

**Comment by Hussein-Mahfouz** [comment]
I have mad a first pass at using HDBSCAN for clustering lines by using a custom distance matrix. The distance between lines is based on equation 3 [here](https://dl.acm.org/doi/abs/10.1145/3152178.3152189). Initial results with minPts = 50:

![cluster](https://github.com/Hussein-Mahfouz/drt-potential/assets/45176416/25a7dd79-e8d8-436a-8432-104dbc9c00ee)

This is just proof that the distance function works, but there are many issues:

- I'm using the MSOA od matrix and each line is treated equally. It is not weighted based on number of people commuting 
- The od matrix is between MSOA centroids. We have clusters grouped by their endpoints in the outer MSOAs because these MSOAs are bigger than the ones in the center - larger distance between their centroids and neighbouring centroids makes it more likely that they are in their own cluster

To Do:

- [ ] [1] handle MAUP due to variable zone sizes. Options: 
    - [ ] use OA level data (MVP)
    - [ ] use uniform hexagon grid
    - [ ] use OD jitter to distribute points in each zone based on population distribution (same as atumie)
    
- [ ] [2] Accounting for weights (no. of people between OD pair)
    - [ ] HDBSCAN
        - [ ] find r implementation that uses weights. I don't think there is any
        - [ ] duplicate each flow n times based on number of commuters. This will create a huge distance matrix. To get distance between all desire line pairs for Leeds: 107 MSOAs = $107^2$ flows  = 11, 449 m * 11,449 n distance matrix BUT if we treat each individual commuter separately then the matrix becomes 142,201 m * 142,201 n. The HDBSCAN function is already slow when m > 3,000 so I don't think this will work
    - [ ] **DBSCAN** 
        - [ ] _How do I use the weights parameter in DBSAN? (**this is possibly the best option**)_
    - [ ] Other algorithms that account for weights?
        - [ ] OPTICS?
        
- [ ] [3] Bivariate flow clustering to determine clusters with [LOW PT, HIGH CAR], [LOW PT, LOW CAR] etc
    - [ ] extend DBSCAN

**Comment by Robinlovelace** [comment]
This looks great to me Hussein, no other comment at this stage...

**Comment by Hussein-Mahfouz** [comment]
It seems like I cannot create big matrices using pivot_wider in tidyr https://github.com/tidyverse/tidyr/issues/1097 . This is an issue for point [1] above as it prevents me from going down to the OA (or custom) hexagon level. I need to find another package that allows this

**Comment by Robinlovelace** [comment]
`od` should be able to help. See here https://github.com/Robinlovelace/simodels/pull/33 for some tests, if you can provide a reproducible example to get moving that would help, key question is how many OD pairs are you looking to question?

And what's the max distance you need?

**Comment by Hussein-Mahfouz** [comment]
@Robinlovelace I am looking at all OD pairs _with commuting flows_. I am getting the "distance" between each pair of desire lines using the metric in eq  1 [here](https://onlinelibrary.wiley.com/doi/full/10.1111/gean.12100). I'm not sure how I would use the function you linked me to. I need to think about it. The clustering algorithm takes in a square matrix, so I still need to create a full matrix even if it is full of NAs (that is where I run into memory issue.

I am now able to use the weights parameter in DBSCAN, see here:
https://github.com/Hussein-Mahfouz/drt-potential/blob/57d84707ef4c209de6a10b30fafdb43b0752a8cb/code/demand_cluster_flows.R#L229-L232

The results are still not good and I think this is mainly because I am using MSOA centroids. I will try odjitter to distribute the flows spatially and see how that affects the results

**Comment by Robinlovelace** [comment]
Sounds good, the `{od}` package may be useful, I was suggesting that the code in that PR goes there. Never tried the DBSCAN algorithm, seems good for this use case.

**Comment by Hussein-Mahfouz** [comment]
Do you recommend using the `od_jitter()` function in the od package, or should I stick to the odjitter rust package used in atumie?

**Comment by Robinlovelace** [comment]
> Do you recommend using the `od_jitter()` function in the od package, or should I stick to the odjitter rust package used in atumie?

Good question. I recommend the `odjitter` package, especially for large datasets. Not used or tested `od_jitter()` in a while and it's slow.

**Comment by Hussein-Mahfouz** [comment]
Results are a bit better after jittering. I still don't understand why most lines are in the big cluster 0. 

![Rplot01](https://github.com/Hussein-Mahfouz/drt-potential/assets/45176416/141dc42e-25d8-479a-b94b-d21d8f2b8789)

Things TODO:
- split flows by distance and then cluster: this is based on the preprocessing done in the [Bivariate Flow Clustering](https://www.tandfonline.com/doi/full/10.1080/13658816.2022.2073595) paper
    - option 1: same as paper. Calculate local l function to see if clustering is happening at different scales. I need to figure out how to calculate the local L
    - option 2: split flows into (a) n distance groups using `cut()` or (b) overlapping window groups (to avoid arbitrary thresholds

- Look at effect of distances that weight either the origin or destination higher (see alpha and beta [here](https://onlinelibrary.wiley.com/doi/full/10.1111/gean.12100))

**Comment by Robinlovelace** [comment]
This is great to see and I can think of applications in other projects. Great work Hussein in figuring out spatial clustering of OD data.

**Comment by Hussein-Mahfouz** [comment]
Last commit fixes a mistake with the distance matrix calculation. I was only calculating distances between flows from the same origin zone, so I wasn't using distances for flows that have a different origin zone. Results now show clusters with flows that start in different zones. Still need to work on the points mentioned above

![image](https://github.com/Hussein-Mahfouz/drt-potential/assets/45176416/1b948945-df9e-473f-a954-6db7ab5a4bcc)
