### ISSUE TITLE
Calculate travel demand (actual travel patterns) between zones

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [Hussein-Mahfouz/drt-potential#4]
## Dataset

I need a dataset with actual travel patterns (ideally it would have different purposes and be disaggregated by time of day)

Options include:

1. The Synthetic Population Catalyst dataset (see notes here: https://github.com/Hussein-Mahfouz/Lit-Review/issues/10#issuecomment-1592998427)
2. [The United Kingdom Time Use Survey, 2014-2015](https://timeuse.org/uk-time-use-survey-2014-2015): 
    - This is for a sample of the population only (sample size?). 
    - Does the data have a geographical component? Is it point locations or are activities assigned to an OA? 
    - Given spatial component, the data could still be used to get relative importance of different OD pairs
3. Create an activity-based dataset. Examples
    - [A dynamic microsimulation model for epidemics](https://www.sciencedirect.com/science/article/pii/S0277953621007930?via%3Dihub)
    -[ Synthetic population and travel demand for Paris and Île-de-France based on open and publicly available data](https://www.sciencedirect.com/science/article/pii/S0968090X21003016)

## Trip purposes

What trip purposes should be considered for the MCA measure? (https://github.com/Hussein-Mahfouz/drt-potential/issues/5). Maybe this should be based on the trip purposes in existing datasets / studies:

-  [A dynamic microsimulation model for epidemics](https://www.sciencedirect.com/science/article/pii/S0277953621007930?via%3Dihub): "Currently three activities, other than spending time at home, are simulated in the model: **working**, attending **school** and **shopping**".
- Trip purposes in SPC: shopping/retail, primary school, secondary school, working, staying at home - relevant code [here](https://github.com/alan-turing-institute/uatk-spc/blob/feffb857c6fbbd7c2b3dd1f3cb46e67677185897/synthpop.proto#L196)

**Comment by Hussein-Mahfouz** [comment]
The census 2021 data is not disaggregated by method of travel. The 2011 data was disaggregated - see table [WU03EW](https://www.nomisweb.co.uk/census/2011/wu03EW) 

I emailed census.customerservices@ons.gov.uk and they said that I have to fill out a specific request form to request a dataset ([see link here](https://www.ons.gov.uk/census/censustransformationprogramme/census2021outputs/2021dataproducts/commissionedtables)). They will begin the request processing service in January 2024, but the requests are not free. This is the breakdown: 

![image](https://github.com/Hussein-Mahfouz/drt-potential/assets/45176416/c618e132-d717-4c20-a0bc-3903f40e38cb)

**Comment by Robinlovelace** [comment]
Happy to support this with my personal development account if needs be Hussein, great bit of research.

**Comment by Hussein-Mahfouz** [comment]
Response from ONS (check text in bold). I don't understand how this work would take a month to compile. What do they mean by "tabulate"? If the data exists (like the 2011 census) then it seems like a simple sql query to me. 

> If the data is not available in the ready-made multivariate datasets or using the create a custom dataset tool, you may be able to commission a table to your own specifications.
> 
> However, Origin Destination tables can contain large amounts of data so if you were to commission a dataset it is worth noting the following points:
> 
> Generally, customers don’t request OD workplace at MSOA level. Customers tend to select an area of residence by all the MSOAs of workplace or all the areas of residence by a selected area of workplace.
>  
> This is because we have 7264 MSOAs in England and Wales as area of residence. We have 7264 MSOAs of workplace + categories ‘work in Scotland or Northern Ireland’, ‘Work on an offshore installation’, ‘work outside the UK, ‘No fixed place of work’, so a total 7268 areas.
>  
> **If you multiply 7264 x 7268 = 52,794,752 combinations to cross tabulate just for the geography alone. When this is multiplied by the variable needed, in this case ‘Method of travel to work’ (5 categories for example) 52,794,752 x 5 = 263,973,760 rows.**
>  
> **This is not a manageable file. We can truncate it, but will end up with around 25 to 30 files. The cost would be around £350+VAT for the first file, £175 + VAT for all the remaining files. This represents around a month of work or more. Not all cross tabulations will have counts in, but we still have to tabulate them.**

My response

> Nomisweb has a selection query for census 2011 which allows me to get MSOA-to-MSOA level flows by method of travel to work - table WU03EW ([link to the page](https://www.nomisweb.co.uk/query/construct/summary.asp?mode=construct&version=0&dataset=1208)). The query is capped at 5,000,000 cells. Is there a similar service for census 2021 where I can query MSOA level OD data by method of travel (and stick to a given cap)?
> I have tried the 'create a custom dataset' tool that you mention but i cannot recreate the query from the 2011 census
> 
> For context, I am trying to get MSOA-level OD data by method of travel to work for Leeds (or West Yorkshire if the cap permits)

**Comment by Robinlovelace** [comment]
Keep up the good work Hussein and let me know if I can help in any way.

**Comment by Hussein-Mahfouz** [comment]
Commuting data by mode for census 2021 is available at [WICID](https://wicid.ukdataservice.ac.uk/flowdata/cider/wicid/downloads.php) but you have to log in with a uni account. It's at MSOA level only. 

File name is **ODWP02EW_MSOA**

Thanks for pointing me to this @Robinlovelace !

**Comment by Robinlovelace** [comment]
Crazy they didn't point you, or presumably others, to the free version at WICID no?

**Comment by Hussein-Mahfouz** [comment]
Yeah they basically said the dataset doesn't exist yet ...
